#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Ensure we have updated standard packages
echo "* Updating standard packages.";
pkg_delete -v nodejs smtools zoneinit
pkg_add -v nodejs smtools zoneinit
npm install smartdc -g
npm install jsontool -g

# Configuring image specific packages
echo "* Configuring image specific packages.";
easy_install-2.7 simplejson
easy_install-2.7 pymongo

# Clean up
echo "* Cleaning up."
rm -rf /root/*
rm -rf /.zonecontrol/metadata.sock

# Prepare image for provisioning
sm-prepare-image -y
